### ISSUE TITLE
Proper citation for IMC2020

### ISSUE THREAD

**Issue by ducha-aiki** [jarvisyjw/GV-Bench#1]
Hi,

I would be grateful if instead of footnote for IMC2020 you use an official paper associated with it:

```
@article{Jin2020,
    author={Yuhe Jin and Dmytro Mishkin and Anastasiia Mishchuk and Jiri Matas and Pascal Fua and Kwang Moo Yi and Eduard Trulls},
    title={{Image Matching across Wide Baselines: From Paper to Practice}},
    journal={International Journal of Computer Vision},
    year={2020}
}
```
<img width="593" alt="image" src="https://github.com/user-attachments/assets/35458016-d64f-4236-9694-a8b4bf6bbc8d">

Best, Dmytro

**Comment by jarvisyjw** [comment]
Hi Dr. Mishkin,

Well noted! Actually, I did not know which paper to cite for IMC2020. Thanks for your guy's excellent work.
I will update this citation on the arxiv and the accepted final version for IROS 2024.

Regards,
Jingwen

**Comment by ducha-aiki** [comment]
Thank you!
