### ISSUE TITLE
Homography vs fundamental

### ISSUE THREAD

**Issue by DoongLi** [jarvisyjw/GV-Bench#3]
I noticed this work used the fundamental matrix, but it seems that most of the work still used homography. I think it's a good idea to increase the comparison between the two.

**Comment by jarvisyjw** [comment]
Hi Doong, 
thanks for your interest and advice!

Homography transform assumes the detected keypoints are in the same plane, which might not hold for most of the robotics and autonomous driving scenarios. I actually provided the API for using either the Fundamental Matrix or Homography Matrix:

https://github.com/jarvisyjw/GV-Bench/blob/202b6285b656919fc4c1deb23bda83fa5abbefde/eval.py#L77-L85

So, anyone interested in this topic can replicate the result using homography matrix estimation directly.
Using the Fundamental Matrix for Geometric Verification actually adopts the Fundamental Matrix from the beginning as it originates from the epipolar constraint. 
Also, you can check out [Doppelgangers](https://github.com/RuojinCai/doppelgangers), a learning-based verification method. The baseline geometric verification compared in this work also adopts the Fundamental Matrix estimation.

I will mark this issue as closed, but feel free to reopen it anytime.
